// user
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

// search
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const SET_SEARCH_CONDITION = 'SET_SEARCH_CONDITION';
export const CHANGE_COLUMN_VISIBILITY = 'CHANGE_COLUMN_VISIBILITY';
export const ADD_DATE_RANGE = 'ADD_DATE_RANGE';
export const REMOVE_DATE_RANGE = 'REMOVE_DATE_RANGE';
export const RESET_DATE_RANGE = 'RESET_DATE_RANGE';
export const SELECT_CONDITION = 'SELECT_CONDITION';
export const ADD_CONDITION = 'ADD_CONDITION';
export const REMOVE_CONDITION = 'REMOVE_CONDITION';
