// user
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

// search
export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const CHANGE_COLUMN_VISIBILITY = 'CHANGE_COLUMN_VISIBILITY';
export const CHANGE_SORT_METHOD = 'CHANGE_SORT_METHOD';
